// Code generated by protoc-gen-go. DO NOT EDIT.
// source: enum.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReceiverType int32

const (
	ReceiverType_RT_UNKNOWN ReceiverType = 0
	ReceiverType_RT_USER    ReceiverType = 1
	ReceiverType_RT_GROUP   ReceiverType = 2
)

var ReceiverType_name = map[int32]string{
	0: "RT_UNKNOWN",
	1: "RT_USER",
	2: "RT_GROUP",
}

var ReceiverType_value = map[string]int32{
	"RT_UNKNOWN": 0,
	"RT_USER":    1,
	"RT_GROUP":   2,
}

func (x ReceiverType) String() string {
	return proto.EnumName(ReceiverType_name, int32(x))
}

func (ReceiverType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_13a9f1b5947140c8, []int{0}
}

type SenderType int32

const (
	SenderType_ST_UNKNOWN  SenderType = 0
	SenderType_ST_SYSTEM   SenderType = 1
	SenderType_ST_USER     SenderType = 2
	SenderType_ST_BUSINESS SenderType = 3
)

var SenderType_name = map[int32]string{
	0: "ST_UNKNOWN",
	1: "ST_SYSTEM",
	2: "ST_USER",
	3: "ST_BUSINESS",
}

var SenderType_value = map[string]int32{
	"ST_UNKNOWN":  0,
	"ST_SYSTEM":   1,
	"ST_USER":     2,
	"ST_BUSINESS": 3,
}

func (x SenderType) String() string {
	return proto.EnumName(SenderType_name, int32(x))
}

func (SenderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_13a9f1b5947140c8, []int{1}
}

type MessageStatus int32

const (
	MessageStatus_MS_UNKNOWN MessageStatus = 0
	MessageStatus_MS_NORMAL  MessageStatus = 1
	MessageStatus_MS_RECALL  MessageStatus = 2
)

var MessageStatus_name = map[int32]string{
	0: "MS_UNKNOWN",
	1: "MS_NORMAL",
	2: "MS_RECALL",
}

var MessageStatus_value = map[string]int32{
	"MS_UNKNOWN": 0,
	"MS_NORMAL":  1,
	"MS_RECALL":  2,
}

func (x MessageStatus) String() string {
	return proto.EnumName(MessageStatus_name, int32(x))
}

func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_13a9f1b5947140c8, []int{2}
}

type PushCode int32

const (
	PushCode_PC_ADD_DEFAULT PushCode = 0
)

var PushCode_name = map[int32]string{
	0: "PC_ADD_DEFAULT",
}

var PushCode_value = map[string]int32{
	"PC_ADD_DEFAULT": 0,
}

func (x PushCode) String() string {
	return proto.EnumName(PushCode_name, int32(x))
}

func (PushCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_13a9f1b5947140c8, []int{3}
}

// 包类型
type PackageType int32

const (
	PackageType_PT_UNKNOWN   PackageType = 0
	PackageType_PT_SIGN_IN   PackageType = 1
	PackageType_PT_SYNC      PackageType = 2
	PackageType_PT_HEARTBEAT PackageType = 3
	PackageType_PT_MESSAGE   PackageType = 4
)

var PackageType_name = map[int32]string{
	0: "PT_UNKNOWN",
	1: "PT_SIGN_IN",
	2: "PT_SYNC",
	3: "PT_HEARTBEAT",
	4: "PT_MESSAGE",
}

var PackageType_value = map[string]int32{
	"PT_UNKNOWN":   0,
	"PT_SIGN_IN":   1,
	"PT_SYNC":      2,
	"PT_HEARTBEAT": 3,
	"PT_MESSAGE":   4,
}

func (x PackageType) String() string {
	return proto.EnumName(PackageType_name, int32(x))
}

func (PackageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_13a9f1b5947140c8, []int{4}
}

// 消息类型
type MessageType int32

const (
	MessageType_MT_UNKNOWN  MessageType = 0
	MessageType_MT_TEXT     MessageType = 1
	MessageType_MT_FACE     MessageType = 2
	MessageType_MT_VOICE    MessageType = 3
	MessageType_MT_IMAGE    MessageType = 4
	MessageType_MT_FILE     MessageType = 5
	MessageType_MT_LOCATION MessageType = 6
	MessageType_MT_COMMAND  MessageType = 7
	MessageType_MT_CUSTOM   MessageType = 8
)

var MessageType_name = map[int32]string{
	0: "MT_UNKNOWN",
	1: "MT_TEXT",
	2: "MT_FACE",
	3: "MT_VOICE",
	4: "MT_IMAGE",
	5: "MT_FILE",
	6: "MT_LOCATION",
	7: "MT_COMMAND",
	8: "MT_CUSTOM",
}

var MessageType_value = map[string]int32{
	"MT_UNKNOWN":  0,
	"MT_TEXT":     1,
	"MT_FACE":     2,
	"MT_VOICE":    3,
	"MT_IMAGE":    4,
	"MT_FILE":     5,
	"MT_LOCATION": 6,
	"MT_COMMAND":  7,
	"MT_CUSTOM":   8,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_13a9f1b5947140c8, []int{5}
}

func init() {
	proto.RegisterEnum("pb.ReceiverType", ReceiverType_name, ReceiverType_value)
	proto.RegisterEnum("pb.SenderType", SenderType_name, SenderType_value)
	proto.RegisterEnum("pb.MessageStatus", MessageStatus_name, MessageStatus_value)
	proto.RegisterEnum("pb.PushCode", PushCode_name, PushCode_value)
	proto.RegisterEnum("pb.PackageType", PackageType_name, PackageType_value)
	proto.RegisterEnum("pb.MessageType", MessageType_name, MessageType_value)
}

func init() { proto.RegisterFile("enum.proto", fileDescriptor_13a9f1b5947140c8) }

var fileDescriptor_13a9f1b5947140c8 = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x86, 0x37, 0x29, 0xec, 0x96, 0x49, 0x77, 0x19, 0xf9, 0x01, 0x78, 0x80, 0x1c, 0xb8, 0x70,
	0xe2, 0xc0, 0xc1, 0xeb, 0x78, 0x8b, 0x45, 0x6c, 0x47, 0x9e, 0x09, 0xb0, 0x12, 0x92, 0x95, 0x6d,
	0xad, 0x82, 0x10, 0x6d, 0xd5, 0xb4, 0x48, 0xbc, 0x05, 0x8f, 0x8c, 0xd2, 0xa6, 0xa2, 0x70, 0xfc,
	0xa4, 0xf9, 0x3f, 0xff, 0xfa, 0x0d, 0x90, 0xd6, 0x87, 0x1f, 0xaf, 0xb7, 0xbb, 0xcd, 0x7e, 0x23,
	0xf2, 0xed, 0x53, 0xf9, 0x16, 0x66, 0x21, 0x2d, 0xd2, 0xb7, 0x9f, 0x69, 0xc7, 0xbf, 0xb6, 0x49,
	0xdc, 0x01, 0x04, 0x8e, 0xad, 0xfb, 0xe0, 0xfc, 0x27, 0x87, 0x57, 0xa2, 0x80, 0x9b, 0x81, 0x49,
	0x07, 0xcc, 0xc4, 0x0c, 0xa6, 0x81, 0xe3, 0x3c, 0xf8, 0xb6, 0xc1, 0xbc, 0x34, 0x00, 0x94, 0xd6,
	0xcb, 0xbf, 0x41, 0xba, 0x0c, 0xde, 0xc2, 0x0b, 0xe2, 0x48, 0x8f, 0xc4, 0xda, 0x62, 0x36, 0x78,
	0x68, 0xf4, 0xe4, 0xe2, 0x25, 0x14, 0xc4, 0xf1, 0xbe, 0x25, 0xe3, 0x34, 0x11, 0x4e, 0xca, 0x77,
	0x70, 0x6b, 0x53, 0xdf, 0x77, 0xab, 0x44, 0xfb, 0x6e, 0x7f, 0xe8, 0x07, 0x9b, 0xa5, 0x7f, 0x6d,
	0x96, 0xa2, 0xf3, 0xc1, 0xca, 0x1a, 0xb3, 0x11, 0x83, 0x56, 0xb2, 0xae, 0x31, 0x2f, 0x5f, 0xc1,
	0xb4, 0x39, 0xf4, 0x5f, 0xd5, 0x66, 0x99, 0x84, 0x80, 0xbb, 0x46, 0x45, 0x59, 0x55, 0xb1, 0xd2,
	0x0f, 0xb2, 0xad, 0x19, 0xaf, 0xca, 0x2f, 0x50, 0x34, 0xdd, 0xe2, 0x7b, 0xb7, 0x4a, 0xe7, 0xaa,
	0xcd, 0x65, 0xd5, 0x13, 0x93, 0x99, 0xbb, 0x68, 0xdc, 0xa9, 0xeb, 0xc0, 0x8f, 0x4e, 0x61, 0x2e,
	0x10, 0x66, 0x0d, 0xc7, 0xf7, 0x5a, 0x06, 0xbe, 0xd7, 0x92, 0x71, 0x32, 0x9e, 0x5b, 0x4d, 0x24,
	0xe7, 0x1a, 0x9f, 0x95, 0xbf, 0x33, 0x28, 0xc6, 0xf6, 0x67, 0xbd, 0xfd, 0x6f, 0x42, 0xcb, 0x91,
	0xf5, 0x67, 0x3e, 0xb9, 0x2d, 0xc7, 0x07, 0xa9, 0x34, 0xe6, 0xc3, 0x9e, 0x96, 0xe3, 0x47, 0x6f,
	0x94, 0xc6, 0xc9, 0x48, 0xc6, 0x1e, 0xad, 0xe7, 0x43, 0x53, 0x6b, 0x7c, 0x3e, 0x0c, 0x66, 0x39,
	0xd6, 0x5e, 0x49, 0x36, 0xde, 0xe1, 0xf5, 0xf8, 0x86, 0xf2, 0xd6, 0x4a, 0x57, 0xe1, 0xcd, 0x71,
	0x10, 0x8e, 0xaa, 0x25, 0xf6, 0x16, 0xa7, 0x4f, 0xd7, 0xc7, 0x0f, 0x7e, 0xf3, 0x27, 0x00, 0x00,
	0xff, 0xff, 0xf0, 0xde, 0x7e, 0xab, 0xee, 0x01, 0x00, 0x00,
}
