// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Sender 发送者
type Sender struct {
	SenderType           SenderType `protobuf:"varint,1,opt,name=sender_type,json=senderType,proto3,enum=pb.SenderType" json:"sender_type,omitempty"`
	SenderId             int64      `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Avatar               string     `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Nickname             string     `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Sender) Reset()         { *m = Sender{} }
func (m *Sender) String() string { return proto.CompactTextString(m) }
func (*Sender) ProtoMessage()    {}
func (*Sender) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Sender) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sender.Unmarshal(m, b)
}
func (m *Sender) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sender.Marshal(b, m, deterministic)
}
func (m *Sender) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sender.Merge(m, src)
}
func (m *Sender) XXX_Size() int {
	return xxx_messageInfo_Sender.Size(m)
}
func (m *Sender) XXX_DiscardUnknown() {
	xxx_messageInfo_Sender.DiscardUnknown(m)
}

var xxx_messageInfo_Sender proto.InternalMessageInfo

func (m *Sender) GetSenderType() SenderType {
	if m != nil {
		return m.SenderType
	}
	return SenderType_ST_UNKNOWN
}

func (m *Sender) GetSenderId() int64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *Sender) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Sender) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

// 消息
type Message struct {
	Sender               *Sender       `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	ReceiverType         ReceiverType  `protobuf:"varint,2,opt,name=receiver_type,json=receiverType,proto3,enum=pb.ReceiverType" json:"receiver_type,omitempty"`
	ReceiverId           int64         `protobuf:"varint,3,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	ToUserIds            []int64       `protobuf:"varint,4,rep,packed,name=to_user_ids,json=toUserIds,proto3" json:"to_user_ids,omitempty"`
	MessageType          MessageType   `protobuf:"varint,5,opt,name=message_type,json=messageType,proto3,enum=pb.MessageType" json:"message_type,omitempty"`
	MessageContent       []byte        `protobuf:"bytes,6,opt,name=message_content,json=messageContent,proto3" json:"message_content,omitempty"`
	Seq                  int64         `protobuf:"varint,7,opt,name=seq,proto3" json:"seq,omitempty"`
	SendTime             int64         `protobuf:"varint,8,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	Status               MessageStatus `protobuf:"varint,9,opt,name=status,proto3,enum=pb.MessageStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSender() *Sender {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Message) GetReceiverType() ReceiverType {
	if m != nil {
		return m.ReceiverType
	}
	return ReceiverType_RT_UNKNOWN
}

func (m *Message) GetReceiverId() int64 {
	if m != nil {
		return m.ReceiverId
	}
	return 0
}

func (m *Message) GetToUserIds() []int64 {
	if m != nil {
		return m.ToUserIds
	}
	return nil
}

func (m *Message) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_MT_UNKNOWN
}

func (m *Message) GetMessageContent() []byte {
	if m != nil {
		return m.MessageContent
	}
	return nil
}

func (m *Message) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Message) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

func (m *Message) GetStatus() MessageStatus {
	if m != nil {
		return m.Status
	}
	return MessageStatus_MS_UNKNOWN
}

// 消息投递
type MessageSend struct {
	Message              *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageSend) Reset()         { *m = MessageSend{} }
func (m *MessageSend) String() string { return proto.CompactTextString(m) }
func (*MessageSend) ProtoMessage()    {}
func (*MessageSend) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *MessageSend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageSend.Unmarshal(m, b)
}
func (m *MessageSend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageSend.Marshal(b, m, deterministic)
}
func (m *MessageSend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageSend.Merge(m, src)
}
func (m *MessageSend) XXX_Size() int {
	return xxx_messageInfo_MessageSend.Size(m)
}
func (m *MessageSend) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageSend.DiscardUnknown(m)
}

var xxx_messageInfo_MessageSend proto.InternalMessageInfo

func (m *MessageSend) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

// 上行数据
type Input struct {
	Type                 PackageType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.PackageType" json:"type,omitempty"`
	RequestId            int64       `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data                 []byte      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetType() PackageType {
	if m != nil {
		return m.Type
	}
	return PackageType_PT_UNKNOWN
}

func (m *Input) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *Input) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// 下行数据
type Output struct {
	Type                 PackageType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.PackageType" json:"type,omitempty"`
	RequestId            int64       `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Code                 int64       `protobuf:"zigzag64,3,opt,name=code,proto3" json:"code,omitempty"`
	Message              string      `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []byte      `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (m *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(m, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetType() PackageType {
	if m != nil {
		return m.Type
	}
	return PackageType_PT_UNKNOWN
}

func (m *Output) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *Output) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Output) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Output) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// 设备登录
type SignInInput struct {
	DeviceId             int64    `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInInput) Reset()         { *m = SignInInput{} }
func (m *SignInInput) String() string { return proto.CompactTextString(m) }
func (*SignInInput) ProtoMessage()    {}
func (*SignInInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *SignInInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInInput.Unmarshal(m, b)
}
func (m *SignInInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInInput.Marshal(b, m, deterministic)
}
func (m *SignInInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInInput.Merge(m, src)
}
func (m *SignInInput) XXX_Size() int {
	return xxx_messageInfo_SignInInput.Size(m)
}
func (m *SignInInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInInput.DiscardUnknown(m)
}

var xxx_messageInfo_SignInInput proto.InternalMessageInfo

func (m *SignInInput) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *SignInInput) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SignInInput) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// 消息同步上行
type SyncInput struct {
	Seq                  int64    `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncInput) Reset()         { *m = SyncInput{} }
func (m *SyncInput) String() string { return proto.CompactTextString(m) }
func (*SyncInput) ProtoMessage()    {}
func (*SyncInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *SyncInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncInput.Unmarshal(m, b)
}
func (m *SyncInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncInput.Marshal(b, m, deterministic)
}
func (m *SyncInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncInput.Merge(m, src)
}
func (m *SyncInput) XXX_Size() int {
	return xxx_messageInfo_SyncInput.Size(m)
}
func (m *SyncInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncInput.DiscardUnknown(m)
}

var xxx_messageInfo_SyncInput proto.InternalMessageInfo

func (m *SyncInput) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

// 消息同步响应
type SyncOutput struct {
	Messages             []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore              bool       `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SyncOutput) Reset()         { *m = SyncOutput{} }
func (m *SyncOutput) String() string { return proto.CompactTextString(m) }
func (*SyncOutput) ProtoMessage()    {}
func (*SyncOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *SyncOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncOutput.Unmarshal(m, b)
}
func (m *SyncOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncOutput.Marshal(b, m, deterministic)
}
func (m *SyncOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncOutput.Merge(m, src)
}
func (m *SyncOutput) XXX_Size() int {
	return xxx_messageInfo_SyncOutput.Size(m)
}
func (m *SyncOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncOutput.DiscardUnknown(m)
}

var xxx_messageInfo_SyncOutput proto.InternalMessageInfo

func (m *SyncOutput) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *SyncOutput) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

// MessageACK 投递回执
type MessageACK struct {
	DeviceAck            int64    `protobuf:"varint,2,opt,name=device_ack,json=deviceAck,proto3" json:"device_ack,omitempty"`
	ReceiveTime          int64    `protobuf:"varint,3,opt,name=receive_time,json=receiveTime,proto3" json:"receive_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageACK) Reset()         { *m = MessageACK{} }
func (m *MessageACK) String() string { return proto.CompactTextString(m) }
func (*MessageACK) ProtoMessage()    {}
func (*MessageACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *MessageACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageACK.Unmarshal(m, b)
}
func (m *MessageACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageACK.Marshal(b, m, deterministic)
}
func (m *MessageACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageACK.Merge(m, src)
}
func (m *MessageACK) XXX_Size() int {
	return xxx_messageInfo_MessageACK.Size(m)
}
func (m *MessageACK) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageACK.DiscardUnknown(m)
}

var xxx_messageInfo_MessageACK proto.InternalMessageInfo

func (m *MessageACK) GetDeviceAck() int64 {
	if m != nil {
		return m.DeviceAck
	}
	return 0
}

func (m *MessageACK) GetReceiveTime() int64 {
	if m != nil {
		return m.ReceiveTime
	}
	return 0
}

// SyncReq 同步消息请求
type SyncReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId             int64    `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Seq                  int64    `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncReq) Reset()         { *m = SyncReq{} }
func (m *SyncReq) String() string { return proto.CompactTextString(m) }
func (*SyncReq) ProtoMessage()    {}
func (*SyncReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}

func (m *SyncReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncReq.Unmarshal(m, b)
}
func (m *SyncReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncReq.Marshal(b, m, deterministic)
}
func (m *SyncReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncReq.Merge(m, src)
}
func (m *SyncReq) XXX_Size() int {
	return xxx_messageInfo_SyncReq.Size(m)
}
func (m *SyncReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncReq.DiscardUnknown(m)
}

var xxx_messageInfo_SyncReq proto.InternalMessageInfo

func (m *SyncReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SyncReq) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *SyncReq) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

// SyncResp 同步消息响应
type SyncResp struct {
	Messages             []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore              bool       `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SyncResp) Reset()         { *m = SyncResp{} }
func (m *SyncResp) String() string { return proto.CompactTextString(m) }
func (*SyncResp) ProtoMessage()    {}
func (*SyncResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{10}
}

func (m *SyncResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncResp.Unmarshal(m, b)
}
func (m *SyncResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncResp.Marshal(b, m, deterministic)
}
func (m *SyncResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncResp.Merge(m, src)
}
func (m *SyncResp) XXX_Size() int {
	return xxx_messageInfo_SyncResp.Size(m)
}
func (m *SyncResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncResp.DiscardUnknown(m)
}

var xxx_messageInfo_SyncResp proto.InternalMessageInfo

func (m *SyncResp) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *SyncResp) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

// MessageACKReq 消息回执请求
type MessageACKReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId             int64    `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceAck            int64    `protobuf:"varint,3,opt,name=device_ack,json=deviceAck,proto3" json:"device_ack,omitempty"`
	ReceiveTime          int64    `protobuf:"varint,4,opt,name=receive_time,json=receiveTime,proto3" json:"receive_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageACKReq) Reset()         { *m = MessageACKReq{} }
func (m *MessageACKReq) String() string { return proto.CompactTextString(m) }
func (*MessageACKReq) ProtoMessage()    {}
func (*MessageACKReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{11}
}

func (m *MessageACKReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageACKReq.Unmarshal(m, b)
}
func (m *MessageACKReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageACKReq.Marshal(b, m, deterministic)
}
func (m *MessageACKReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageACKReq.Merge(m, src)
}
func (m *MessageACKReq) XXX_Size() int {
	return xxx_messageInfo_MessageACKReq.Size(m)
}
func (m *MessageACKReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageACKReq.DiscardUnknown(m)
}

var xxx_messageInfo_MessageACKReq proto.InternalMessageInfo

func (m *MessageACKReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MessageACKReq) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *MessageACKReq) GetDeviceAck() int64 {
	if m != nil {
		return m.DeviceAck
	}
	return 0
}

func (m *MessageACKReq) GetReceiveTime() int64 {
	if m != nil {
		return m.ReceiveTime
	}
	return 0
}

// MessageACKResp 消息架势响应
type MessageACKResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageACKResp) Reset()         { *m = MessageACKResp{} }
func (m *MessageACKResp) String() string { return proto.CompactTextString(m) }
func (*MessageACKResp) ProtoMessage()    {}
func (*MessageACKResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{12}
}

func (m *MessageACKResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageACKResp.Unmarshal(m, b)
}
func (m *MessageACKResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageACKResp.Marshal(b, m, deterministic)
}
func (m *MessageACKResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageACKResp.Merge(m, src)
}
func (m *MessageACKResp) XXX_Size() int {
	return xxx_messageInfo_MessageACKResp.Size(m)
}
func (m *MessageACKResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageACKResp.DiscardUnknown(m)
}

var xxx_messageInfo_MessageACKResp proto.InternalMessageInfo

type Text struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Text) Reset()         { *m = Text{} }
func (m *Text) String() string { return proto.CompactTextString(m) }
func (*Text) ProtoMessage()    {}
func (*Text) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{13}
}

func (m *Text) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Text.Unmarshal(m, b)
}
func (m *Text) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Text.Marshal(b, m, deterministic)
}
func (m *Text) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Text.Merge(m, src)
}
func (m *Text) XXX_Size() int {
	return xxx_messageInfo_Text.Size(m)
}
func (m *Text) XXX_DiscardUnknown() {
	xxx_messageInfo_Text.DiscardUnknown(m)
}

var xxx_messageInfo_Text proto.InternalMessageInfo

func (m *Text) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Face struct {
	FaceId               string   `protobuf:"bytes,1,opt,name=face_id,json=faceId,proto3" json:"face_id,omitempty"`
	FaceUrl              string   `protobuf:"bytes,2,opt,name=face_url,json=faceUrl,proto3" json:"face_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Face) Reset()         { *m = Face{} }
func (m *Face) String() string { return proto.CompactTextString(m) }
func (*Face) ProtoMessage()    {}
func (*Face) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{14}
}

func (m *Face) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Face.Unmarshal(m, b)
}
func (m *Face) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Face.Marshal(b, m, deterministic)
}
func (m *Face) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Face.Merge(m, src)
}
func (m *Face) XXX_Size() int {
	return xxx_messageInfo_Face.Size(m)
}
func (m *Face) XXX_DiscardUnknown() {
	xxx_messageInfo_Face.DiscardUnknown(m)
}

var xxx_messageInfo_Face proto.InternalMessageInfo

func (m *Face) GetFaceId() string {
	if m != nil {
		return m.FaceId
	}
	return ""
}

func (m *Face) GetFaceUrl() string {
	if m != nil {
		return m.FaceUrl
	}
	return ""
}

type Voice struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Size                 int64    `protobuf:"zigzag64,2,opt,name=size,proto3" json:"size,omitempty"`
	Duration             int64    `protobuf:"zigzag64,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Url                  int64    `protobuf:"zigzag64,4,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Voice) Reset()         { *m = Voice{} }
func (m *Voice) String() string { return proto.CompactTextString(m) }
func (*Voice) ProtoMessage()    {}
func (*Voice) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{15}
}

func (m *Voice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Voice.Unmarshal(m, b)
}
func (m *Voice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Voice.Marshal(b, m, deterministic)
}
func (m *Voice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Voice.Merge(m, src)
}
func (m *Voice) XXX_Size() int {
	return xxx_messageInfo_Voice.Size(m)
}
func (m *Voice) XXX_DiscardUnknown() {
	xxx_messageInfo_Voice.DiscardUnknown(m)
}

var xxx_messageInfo_Voice proto.InternalMessageInfo

func (m *Voice) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Voice) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Voice) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Voice) GetUrl() int64 {
	if m != nil {
		return m.Url
	}
	return 0
}

type Image struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Width                int64    `protobuf:"zigzag64,2,opt,name=width,proto3" json:"width,omitempty"`
	Height               int64    `protobuf:"zigzag64,3,opt,name=height,proto3" json:"height,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	ThumbnailUrl         string   `protobuf:"bytes,5,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{16}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Image) GetWidth() int64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Image) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Image) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Image) GetThumbnailUrl() string {
	if m != nil {
		return m.ThumbnailUrl
	}
	return ""
}

type File struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size                 int64    `protobuf:"zigzag64,3,opt,name=size,proto3" json:"size,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{17}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*Sender)(nil), "pb.Sender")
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterType((*MessageSend)(nil), "pb.MessageSend")
	proto.RegisterType((*Input)(nil), "pb.Input")
	proto.RegisterType((*Output)(nil), "pb.Output")
	proto.RegisterType((*SignInInput)(nil), "pb.SignInInput")
	proto.RegisterType((*SyncInput)(nil), "pb.SyncInput")
	proto.RegisterType((*SyncOutput)(nil), "pb.SyncOutput")
	proto.RegisterType((*MessageACK)(nil), "pb.MessageACK")
	proto.RegisterType((*SyncReq)(nil), "pb.SyncReq")
	proto.RegisterType((*SyncResp)(nil), "pb.SyncResp")
	proto.RegisterType((*MessageACKReq)(nil), "pb.MessageACKReq")
	proto.RegisterType((*MessageACKResp)(nil), "pb.MessageACKResp")
	proto.RegisterType((*Text)(nil), "pb.Text")
	proto.RegisterType((*Face)(nil), "pb.Face")
	proto.RegisterType((*Voice)(nil), "pb.Voice")
	proto.RegisterType((*Image)(nil), "pb.Image")
	proto.RegisterType((*File)(nil), "pb.File")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 854 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcd, 0x6e, 0xe4, 0x44,
	0x10, 0x96, 0xc7, 0x1e, 0xcf, 0xb8, 0x3c, 0x99, 0x0d, 0xc5, 0x0a, 0xcc, 0xac, 0x16, 0x66, 0xbd,
	0x42, 0x3b, 0x5c, 0x82, 0x94, 0x05, 0x0e, 0xdc, 0x56, 0x91, 0x56, 0x1a, 0xa1, 0x5d, 0x42, 0x27,
	0x8b, 0xb4, 0xa7, 0x91, 0x63, 0x37, 0x99, 0xd6, 0xc4, 0x3f, 0x71, 0xb7, 0xc3, 0x06, 0x71, 0x47,
	0xe2, 0xc0, 0x13, 0xf0, 0x68, 0x3c, 0x0c, 0xea, 0xea, 0xf6, 0x4f, 0x26, 0x07, 0x24, 0x94, 0x5b,
	0xfd, 0x74, 0x57, 0x7d, 0xdf, 0xe7, 0x2a, 0x37, 0x1c, 0xe4, 0x5c, 0xca, 0xe4, 0x92, 0x1f, 0x55,
	0x75, 0xa9, 0x4a, 0x1c, 0x55, 0x17, 0x0b, 0xe0, 0x45, 0x93, 0x1b, 0x7f, 0x01, 0x8d, 0xe4, 0xb5,
	0xb1, 0xe3, 0x3f, 0x1d, 0xf0, 0xcf, 0x78, 0x91, 0xf1, 0x1a, 0xbf, 0x86, 0x50, 0x92, 0xb5, 0x51,
	0xb7, 0x15, 0x8f, 0x9c, 0xa5, 0xb3, 0x9a, 0x1f, 0xcf, 0x8f, 0xaa, 0x8b, 0x23, 0x73, 0xe0, 0xfc,
	0xb6, 0xe2, 0x0c, 0x64, 0x67, 0xe3, 0x13, 0x08, 0xec, 0x05, 0x91, 0x45, 0xa3, 0xa5, 0xb3, 0x72,
	0xd9, 0xd4, 0x04, 0xd6, 0x19, 0x7e, 0x02, 0x7e, 0x72, 0x93, 0xa8, 0xa4, 0x8e, 0xdc, 0xa5, 0xb3,
	0x0a, 0x98, 0xf5, 0x70, 0x01, 0xd3, 0x42, 0xa4, 0xbb, 0x22, 0xc9, 0x79, 0xe4, 0x51, 0xa6, 0xf3,
	0xe3, 0x7f, 0x46, 0x30, 0x79, 0x63, 0xa0, 0x63, 0x0c, 0xbe, 0xa9, 0x45, 0x40, 0xc2, 0x63, 0xe8,
	0x81, 0x30, 0x9b, 0xc1, 0x6f, 0xe1, 0xa0, 0xe6, 0x29, 0x17, 0x37, 0x2d, 0xe6, 0x11, 0x61, 0x3e,
	0xd4, 0x47, 0x99, 0x4d, 0x10, 0xea, 0x59, 0x3d, 0xf0, 0xf0, 0x0b, 0x08, 0xbb, 0x6b, 0x22, 0x23,
	0x7c, 0x2e, 0x83, 0x36, 0xb4, 0xce, 0xf0, 0x73, 0x08, 0x55, 0xb9, 0xd1, 0x2a, 0x6d, 0x44, 0x26,
	0x23, 0x6f, 0xe9, 0xae, 0x5c, 0x16, 0xa8, 0xf2, 0x9d, 0xd4, 0x69, 0x89, 0xc7, 0x30, 0xb3, 0x0a,
	0x9b, 0xb6, 0x63, 0x6a, 0xfb, 0x48, 0xb7, 0xb5, 0xf0, 0xa9, 0x6b, 0x98, 0xf7, 0x0e, 0xbe, 0x80,
	0x47, 0xed, 0x9d, 0xb4, 0x2c, 0x14, 0x2f, 0x54, 0xe4, 0x2f, 0x9d, 0xd5, 0x8c, 0xcd, 0x6d, 0xf8,
	0xc4, 0x44, 0xf1, 0x10, 0x5c, 0xc9, 0xaf, 0xa3, 0x09, 0xa1, 0xd2, 0x66, 0xab, 0xf3, 0x46, 0x89,
	0x9c, 0x47, 0xd3, 0x5e, 0xe7, 0x73, 0x91, 0x73, 0xfc, 0x0a, 0x7c, 0xa9, 0x12, 0xd5, 0xc8, 0x28,
	0x20, 0x14, 0x1f, 0x0d, 0x50, 0x9c, 0x51, 0x82, 0xd9, 0x03, 0xf1, 0x37, 0x10, 0xb6, 0x09, 0x5e,
	0x64, 0xf8, 0x25, 0x4c, 0x6c, 0x6b, 0x2b, 0x71, 0x38, 0xb8, 0xca, 0xda, 0x5c, 0xbc, 0x81, 0xf1,
	0xba, 0xa8, 0x1a, 0x85, 0xcf, 0xc1, 0x1b, 0x0c, 0x06, 0xb1, 0x3d, 0x4d, 0xd2, 0x5d, 0xcb, 0x96,
	0x92, 0xf8, 0x14, 0xa0, 0xe6, 0xd7, 0x0d, 0x97, 0xaa, 0x1f, 0x8a, 0xc0, 0x46, 0xd6, 0x19, 0x22,
	0x78, 0x59, 0xa2, 0x12, 0xd2, 0x7c, 0xc6, 0xc8, 0x8e, 0xff, 0x72, 0xc0, 0xff, 0xb1, 0x51, 0x0f,
	0xd8, 0x22, 0x2d, 0x33, 0x4e, 0x2d, 0x90, 0x91, 0x8d, 0x51, 0x4f, 0xd5, 0xcc, 0x5c, 0xeb, 0x76,
	0x80, 0xc6, 0x03, 0x40, 0xef, 0x21, 0x3c, 0x13, 0x97, 0xc5, 0xba, 0x30, 0xbc, 0x9f, 0x40, 0x90,
	0xf1, 0x1b, 0x91, 0x72, 0xdd, 0xce, 0x31, 0xf2, 0x9b, 0xc0, 0x3a, 0xc3, 0x4f, 0x61, 0x62, 0xe7,
	0xc4, 0x22, 0xf1, 0x1b, 0x1a, 0x12, 0x7c, 0x0c, 0x63, 0x55, 0xee, 0x78, 0x61, 0xc7, 0xdf, 0x38,
	0xf1, 0x53, 0x08, 0xce, 0x6e, 0x8b, 0xd4, 0x14, 0xb6, 0x5f, 0xda, 0xe9, 0xbe, 0x74, 0x7c, 0x0a,
	0xa0, 0xd3, 0x56, 0x8d, 0x17, 0x30, 0xb5, 0x30, 0x65, 0xe4, 0x2c, 0xdd, 0xfd, 0x2f, 0xd4, 0x25,
	0xf1, 0x33, 0x98, 0x6e, 0x13, 0xb9, 0xc9, 0xcb, 0xda, 0xac, 0xc0, 0x94, 0x4d, 0xb6, 0x89, 0x7c,
	0x53, 0xd6, 0x3c, 0x7e, 0x0b, 0x60, 0xcf, 0xbf, 0x3a, 0xf9, 0x41, 0x4b, 0x67, 0xa9, 0x24, 0xe9,
	0xae, 0x95, 0xce, 0x44, 0x5e, 0xa5, 0x3b, 0x7c, 0x06, 0xed, 0xa2, 0x98, 0x59, 0x33, 0x9b, 0xd1,
	0x2e, 0x8b, 0x1e, 0xb7, 0xf8, 0x27, 0x98, 0x68, 0x84, 0x8c, 0x5f, 0x0f, 0xa9, 0x3b, 0x77, 0xa8,
	0xdf, 0x11, 0x6c, 0xb4, 0x27, 0x98, 0x25, 0xed, 0xf6, 0xa4, 0xdf, 0xc2, 0xd4, 0x94, 0x94, 0xd5,
	0x83, 0x50, 0xfe, 0xc3, 0x81, 0x83, 0x9e, 0xf3, 0xff, 0x47, 0x7a, 0x57, 0x2c, 0xf7, 0xbf, 0xc4,
	0xf2, 0xee, 0x8b, 0x75, 0x08, 0xf3, 0x21, 0x10, 0x59, 0xc5, 0x0b, 0xf0, 0xce, 0xf9, 0x07, 0xa5,
	0xc7, 0x4e, 0xf1, 0x0f, 0x8a, 0xe0, 0x04, 0x8c, 0xec, 0xf8, 0x7b, 0xf0, 0x5e, 0x27, 0x29, 0xd7,
	0x68, 0x7f, 0x49, 0xfa, 0x69, 0x0b, 0x98, 0xaf, 0xdd, 0x75, 0xa6, 0x39, 0x53, 0xa2, 0xa9, 0xaf,
	0x08, 0x6c, 0xc0, 0xe8, 0xe0, 0xbb, 0xfa, 0x2a, 0x7e, 0x0f, 0xe3, 0x9f, 0x4b, 0x91, 0x72, 0x9c,
	0xc3, 0xa8, 0xbb, 0x37, 0x12, 0xb4, 0x0d, 0x52, 0xfc, 0x66, 0x34, 0x42, 0x46, 0xb6, 0xfe, 0x05,
	0x67, 0x4d, 0x9d, 0x28, 0x51, 0x16, 0x76, 0x4b, 0x3a, 0x5f, 0x7f, 0x1e, 0x5d, 0xde, 0xa3, 0xb0,
	0x36, 0xe3, 0xdf, 0x61, 0xbc, 0xce, 0xf5, 0xaa, 0xec, 0x97, 0x7e, 0x0c, 0xe3, 0x5f, 0x45, 0xa6,
	0xb6, 0xb6, 0xb6, 0x71, 0xf4, 0x7f, 0x7f, 0xcb, 0xc5, 0xe5, 0x56, 0xd9, 0xd2, 0xd6, 0x1b, 0x16,
	0x0e, 0xa8, 0x30, 0x3e, 0x87, 0x03, 0xb5, 0x6d, 0xf2, 0x8b, 0x22, 0x11, 0x57, 0xc4, 0x69, 0x4c,
	0xb9, 0x59, 0x17, 0xd4, 0xc4, 0x4e, 0xc1, 0x7b, 0x2d, 0xae, 0x86, 0xcd, 0xdd, 0x96, 0x17, 0x3d,
	0x21, 0x46, 0x07, 0xb2, 0x3b, 0xae, 0xee, 0x80, 0xeb, 0xbd, 0xb6, 0xc7, 0x7f, 0x3b, 0xdd, 0x4a,
	0xb0, 0xd3, 0x13, 0xfc, 0x0e, 0x42, 0xfd, 0x37, 0x6c, 0x9f, 0x1d, 0x6c, 0x9f, 0x99, 0xf6, 0x08,
	0xbf, 0x5e, 0x7c, 0x7c, 0x2f, 0x26, 0x2b, 0x7c, 0x06, 0x9e, 0x9e, 0x5a, 0xa4, 0xf9, 0xb4, 0x2b,
	0xb1, 0x98, 0xf5, 0x8e, 0xac, 0xf0, 0xe5, 0x9d, 0xdd, 0x1b, 0xfe, 0x98, 0xcd, 0x5c, 0x2e, 0x70,
	0x3f, 0x24, 0xab, 0x0b, 0x9f, 0xde, 0xe5, 0x97, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x17, 0x72,
	0xe6, 0xc9, 0xc4, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessageRPCClient is the client API for MessageRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessageRPCClient interface {
	// SendMessage 发送消息
	SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error)
	// Sync 消息同步
	Sync(ctx context.Context, in *SyncReq, opts ...grpc.CallOption) (*SyncResp, error)
	// MessageACK 设备收到消息回执
	MessageACK(ctx context.Context, in *MessageACKReq, opts ...grpc.CallOption) (*MessageACKResp, error)
}

type messageRPCClient struct {
	cc *grpc.ClientConn
}

func NewMessageRPCClient(cc *grpc.ClientConn) MessageRPCClient {
	return &messageRPCClient{cc}
}

func (c *messageRPCClient) SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error) {
	out := new(SendMessageResp)
	err := c.cc.Invoke(ctx, "/pb.MessageRPC/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRPCClient) Sync(ctx context.Context, in *SyncReq, opts ...grpc.CallOption) (*SyncResp, error) {
	out := new(SyncResp)
	err := c.cc.Invoke(ctx, "/pb.MessageRPC/Sync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageRPCClient) MessageACK(ctx context.Context, in *MessageACKReq, opts ...grpc.CallOption) (*MessageACKResp, error) {
	out := new(MessageACKResp)
	err := c.cc.Invoke(ctx, "/pb.MessageRPC/MessageACK", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageRPCServer is the server API for MessageRPC service.
type MessageRPCServer interface {
	// SendMessage 发送消息
	SendMessage(context.Context, *SendMessageReq) (*SendMessageResp, error)
	// Sync 消息同步
	Sync(context.Context, *SyncReq) (*SyncResp, error)
	// MessageACK 设备收到消息回执
	MessageACK(context.Context, *MessageACKReq) (*MessageACKResp, error)
}

func RegisterMessageRPCServer(s *grpc.Server, srv MessageRPCServer) {
	s.RegisterService(&_MessageRPC_serviceDesc, srv)
}

func _MessageRPC_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRPCServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MessageRPC/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRPCServer).SendMessage(ctx, req.(*SendMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRPC_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRPCServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MessageRPC/Sync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRPCServer).Sync(ctx, req.(*SyncReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageRPC_MessageACK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageACKReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageRPCServer).MessageACK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MessageRPC/MessageACK",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageRPCServer).MessageACK(ctx, req.(*MessageACKReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MessageRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MessageRPC",
	HandlerType: (*MessageRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _MessageRPC_SendMessage_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _MessageRPC_Sync_Handler,
		},
		{
			MethodName: "MessageACK",
			Handler:    _MessageRPC_MessageACK_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
